fix: missing 'declaration' option in tsconfig
error : ``error TS5052: Option 'declarationDir' cannot be specified without
specifying option 'declaration'.``