refactor: add castings to `tsConfig.options`
Needed because of the below error
```
src/lib/ng-package/entry-point/analyse-sources.transform.ts:39:9 - error TS2322: Type '{ skipLibCheck: true; noLib: true; noEmit: true; types: undefined[]; target: ts.ScriptTarget.ESNext; strict: false; genDir?: string; basePath?: string; skipMetadataEmit?: boolean; strictMetadataEmit?: boolean; ... 133 more ...; disableTypeScriptVersionCheck?: boolean; }' is not assignable to type 'CompilerOptions'.
  Property 'extendedDiagnostics' is incompatible with index signature.
    Type '{ defaultCategory?: DiagnosticCategoryLabel; checks?: { invalidBananaInBox?: DiagnosticCategoryLabel; nullishCoalescingNotNullable?: DiagnosticCategoryLabel; }; }' is not assignable to type 'CompilerOptionsValue | TsConfigSourceFile'.
      Type '{ defaultCategory?: DiagnosticCategoryLabel; checks?: { invalidBananaInBox?: DiagnosticCategoryLabel; nullishCoalescingNotNullable?: DiagnosticCategoryLabel; }; }' is not assignable to type 'MapLike<string[]>'.
        Property 'defaultCategory' is incompatible with index signature.
          Type 'import("@angular/compiler-cli/src/ngtsc/core/api/src/public_options").DiagnosticCategoryLabel' is not assignable to type 'string[]'.

39   const tsConfigOptions: ts.CompilerOptions = {
           ~~~~~~~~~~~~~~~
```