fix: pass file pathes to `postcss.process()`
Motivation: In certain use cases, autoprefixer and browserslist ended up looking up an `undefined` path since postcss explicitly sets plugin options, thus overwriting a file path to `undefined`.

[debug] processAssets /Users/David/Projects/github/dherges/ng-packaged/my-lib to /Users/David/Projects/github/dherges/ng-packaged/.ng_build/ts
[debug] render stylesheet /Users/David/Projects/github/dherges/ng-packaged/my-lib/src/foo/foo.component.scss
[debug] rendering sass for /Users/David/Projects/github/dherges/ng-packaged/my-lib/src/foo/foo.component.scss
[debug] postcss with autoprefixer for /Users/David/Projects/github/dherges/ng-packaged/my-lib/src/foo/foo.component.scss

BUILD ERROR
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at eachParent (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/browserslist/index.js:65:18)
    at getStat (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/browserslist/index.js:79:12)
    at browserslist (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/browserslist/index.js:188:15)
    at Browsers.parse (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/autoprefixer/lib/autoprefixer.js:67:24)
    at plugin (/Users/David/Projects/github/dherges/ng-packaged/node_modules/ng-packagr/node_modules/autoprefixer/lib/autoprefixer.js:78:24)
    at LazyResult.run (/Users/David/Projects/github/dherges/ng-packaged/node_modules/postcss/lib/lazy-result.js:270:20)